/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controla.ArrayCdDatos;
import java.awt.HeadlessException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UsuarioEp
 */
public class VentanaDatos extends javax.swing.JFrame {

    
    int cont,i;
    double total;
    ArrayCdDatos objvec1;
    DefaultListModel modlista=new DefaultListModel();
    DefaultTableModel modcarrito=new DefaultTableModel();
    DefaultTableModel modBuscar=new DefaultTableModel();
    

    public VentanaDatos(String title) throws HeadlessException {
        super(title);
    }
    
    
    public VentanaDatos() {
        initComponents();
        i=4;
        objvec1=new ArrayCdDatos();
        String []titel ={"Cod","Tamaño","Nombre","Valor"}; 
       
        modcarrito.setColumnIdentifiers(titel);
        modBuscar.setColumnIdentifiers(titel);
        tablacarrito.setModel(modcarrito);
        tablaBuscar.setModel(modBuscar);
        cont=0;
        total=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrupo1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txttamaño = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btncargarStock = new javax.swing.JButton();
        rdbtnBuscarNom = new javax.swing.JRadioButton();
        rdbtnBusCodigo1 = new javax.swing.JRadioButton();
        txtbuscar = new javax.swing.JTextField();
        btnLimpiarta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBuscar = new javax.swing.JTable();
        btnAgragarCarrito = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablacarrito = new javax.swing.JTable();
        btnGeneTicket = new javax.swing.JButton();
        totalCarrito = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        elimElemenCarrito = new javax.swing.JButton();
        cantCarrito = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cantStock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Gadugi", 2, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCTO MULTIMEDIA DATOS");

        jLabel6.setText("CODIGO:");

        jScrollPane1.setViewportView(lista1);

        jLabel2.setText("NOMBRE :");

        jLabel3.setText("TAMAÑO EN MB: ");

        jLabel4.setText("PRECIO:");

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btncargarStock.setText("Cargar Invenrario");
        btncargarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarStockActionPerformed(evt);
            }
        });

        btngrupo1.add(rdbtnBuscarNom);
        rdbtnBuscarNom.setText("BuscarNombre");

        btngrupo1.add(rdbtnBusCodigo1);
        rdbtnBusCodigo1.setText("BuscarCodigo");

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        btnLimpiarta.setText("Limpiar tabla");
        btnLimpiarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiartaActionPerformed(evt);
            }
        });

        tablaBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaBuscar);

        btnAgragarCarrito.setText("Agregar al Carro");
        btnAgragarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgragarCarritoActionPerformed(evt);
            }
        });

        tablacarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablacarrito);

        btnGeneTicket.setText("Generar Ticket");
        btnGeneTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneTicketActionPerformed(evt);
            }
        });

        totalCarrito.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Total:");

        elimElemenCarrito.setText("Eliminar");
        elimElemenCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimElemenCarritoActionPerformed(evt);
            }
        });

        cantCarrito.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Cantidad:");

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        jLabel5.setText("Cant:");

        cantStock.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbtnBusCodigo1)
                                .addGap(26, 26, 26)
                                .addComponent(rdbtnBuscarNom)
                                .addGap(26, 26, 26)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cantStock, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btncargarStock)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbuscar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(Limpiar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcodi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(118, 118, 118)))
                        .addGap(55, 55, 55))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarta)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(cantCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(elimElemenCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(totalCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(btnGeneTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnAgragarCarrito)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtcodi, txtnombre, txtprecio, txttamaño});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGeneTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRegistrar)
                                    .addComponent(jLabel5)
                                    .addComponent(cantStock, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdbtnBusCodigo1)
                                    .addComponent(rdbtnBuscarNom)
                                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnbuscar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(btnLimpiarta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(btnAgragarCarrito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(elimElemenCarrito)
                                    .addComponent(cantCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(totalCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Limpiar)
                            .addComponent(btncargarStock))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed
    String ticket;
    private void btnGeneTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneTicketActionPerformed
     for (int j = 0; j < modcarrito.getRowCount(); j++) {
            for (int k = 0; k < modcarrito.getColumnCount(); k++) {
                ticket += modcarrito.getValueAt(j, k).toString() + "                 ";
            }
            ticket += "\n";
        }

        JOptionPane.showMessageDialog(null, "*    Cod      *  Tamaño MB  *      Nombre         *  valor  *\n"
                + "" + ticket + "\n Total a pagar$:" + totalCarrito.getText(), " *FACTURA*", JOptionPane.INFORMATION_MESSAGE);
        ticket = "";
       
    }//GEN-LAST:event_btnGeneTicketActionPerformed

    private void elimElemenCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimElemenCarritoActionPerformed
        int fila;
        String totalAux;
        fila = this.tablacarrito.getSelectedRow();
        if (fila >= 0) {
            totalAux = tablacarrito.getValueAt(fila, 3).toString();
            total -= Double.parseDouble(totalAux);
            totalCarrito.setText("" + total);
            modcarrito.removeRow(fila);
            cont = modcarrito.getRowCount();
            this.cantCarrito.setText("" + cont);
        } else {
            JOptionPane.showMessageDialog(null, " Por favor seleccione el Item que desea eliminar de la tabla ");
        }
    }//GEN-LAST:event_elimElemenCarritoActionPerformed

    
    private void btncargarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarStockActionPerformed
        clearLista();
        for (int z = 0; z < objvec1.getVecdDatos().size(); z++) {
            modlista.add(z, objvec1.getVecdDatos().get(z).getCod() + "" + objvec1.getVecdDatos().get(z).getNompro());
            lista1.setModel(modlista);

        }
    }//GEN-LAST:event_btncargarStockActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        
        clearLista();
        
    }//GEN-LAST:event_LimpiarActionPerformed
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       
        objvec1.agreCddatos(Float.parseFloat(txttamaño.getText()), txtcodi.getText(), txtnombre.getText(), Double.parseDouble(txtprecio.getText()));
        modlista.add(i, objvec1.getVecdDatos().get(i).getCod() + "" + objvec1.getVecdDatos().get(i).getNompro());
        i++;
        cantStock.setText("" + objvec1.getCont());
    }//GEN-LAST:event_btnRegistrarActionPerformed

    String vecAux[] = new String[4];
    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
         
        if (rdbtnBusCodigo1.isSelected()) {
            objvec1.buscar(1, txtbuscar.getText());
            for (int j = 0; j < objvec1.getAux().size(); j++) {
                vecAux[0] = objvec1.getAux().get(j).getCod();
                vecAux[1] = "" + objvec1.getAux().get(j).getTamaño();
                vecAux[2] = objvec1.getAux().get(j).getNompro();
                vecAux[3] = "" + objvec1.getAux().get(j).getPrecio();

                modBuscar.addRow(vecAux);
                tablaBuscar.setModel(modBuscar);

            }

        } else {

            objvec1.buscar(2, txtbuscar.getText());
            for (int j = 0; j < objvec1.getAux().size(); j++) {
                vecAux[0] = objvec1.getAux().get(j).getCod();
                vecAux[1] = objvec1.getAux().get(j).getNompro();
                vecAux[2] = "" + objvec1.getAux().get(j).getTamaño();
                vecAux[3] = "" + objvec1.getAux().get(j).getPrecio();

                modBuscar.addRow(vecAux);
                tablaBuscar.setModel(modBuscar);

            }
        }


    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnLimpiartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiartaActionPerformed
     
        modBuscar.setColumnCount(4);
        modBuscar.setRowCount(0);
  
        
    }//GEN-LAST:event_btnLimpiartaActionPerformed
    int can=0;
    private void btnAgragarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgragarCarritoActionPerformed
       
        String pre;
        
        String data []=new String[4];
        int fila = tablaBuscar.getSelectedRow();
        if (fila>=0) {
            data[0]=tablaBuscar.getValueAt(fila, 0).toString();
            data[1]=tablaBuscar.getValueAt(fila, 1).toString();
            data[2]=tablaBuscar.getValueAt(fila, 2).toString();
            data[3]=tablaBuscar.getValueAt(fila, 3).toString();
            pre=tablaBuscar.getValueAt(fila, 3).toString();
            modcarrito.addRow(data);
            tablacarrito.setModel(modcarrito);
            total+=Double.parseDouble(pre);
            totalCarrito.setText(""+total);
            can=modcarrito.getRowCount();
            cantCarrito.setText(""+can);
        } else {
            JOptionPane.showMessageDialog(null," DEBE SELECCIONAR UN ITEM ","ALERTA",JOptionPane.WARNING_MESSAGE);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnAgragarCarritoActionPerformed

    public void clearLista(){
         modlista = new DefaultListModel();
        lista1.setModel(modlista);
        
        
    }    
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaDatos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton btnAgragarCarrito;
    private javax.swing.JButton btnGeneTicket;
    private javax.swing.JButton btnLimpiarta;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncargarStock;
    private javax.swing.ButtonGroup btngrupo1;
    private javax.swing.JLabel cantCarrito;
    private javax.swing.JLabel cantStock;
    private javax.swing.JButton elimElemenCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lista1;
    private javax.swing.JRadioButton rdbtnBusCodigo1;
    private javax.swing.JRadioButton rdbtnBuscarNom;
    private javax.swing.JTable tablaBuscar;
    private javax.swing.JTable tablacarrito;
    private javax.swing.JLabel totalCarrito;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcodi;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txttamaño;
    // End of variables declaration//GEN-END:variables
}
